# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.CharField(default='NaN', max_length=100),
        ),
    ]
