# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20160913_0311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newspaper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='newspaper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Newspaper'),
        ),
    ]
