# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 00:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20160913_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activeNewspaper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.Newspaper')),
            ],
        ),
    ]
